bugsnag/bugsnag-node

lib/bugsnag.js
src/bugsnag.coffee

Please expose `shouldNotify` function to have the condition to insert the error handler as the event hook affects the performance.
```
if (!Bugsnag.shouldNotify())
server.on("uncaughtException", bugsnag.restifyHandler);
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bugsnag/bugsnag-node/40)

Expose shouldNotify

---

lib/bugsnag.js

I managed to replicate a similar problem to this, though I was
getting an out of memory error not a stack size exceeded error.
This was the fix.

Clean request-info pre-emptively [Fixes #16]?

---

lib/request_info.js

Just upgraded to Bugsnag v1.6.0, but express v4.11.2 started logging this warning:
express deprecated req.host: Use req.hostname instead node_modules/bugsnag/lib/request_info.js:6:46
This should fix this!

Rename req.host to req.hostname

---

lib/notification.js

See: https://github.com/request/request#requestoptions-callback
This fixes a bug where requests weren't being routed through a proxy properly.

The request command requires the url to be part of the options hash.

---

README.md

Sorry, just noticed that PR #67 tweaked the `onBeforeNotify` section in the readme.

Fix the `onBeforeNotify` section in the readme

---

package.json

Currently both `promise` and `request` versions are pinned which makes it impossible to get patched updates within the same major version, see the commit message to a50469d.
It may require a version bump to 1.7, not sure what your policy is.
All tests are green locally.

Relaxes dependency versioning 

---

lib/notification.js

Scrubs cleaned request from the payload in the case that both req and
cleanedRequest are set.
Fixes #69

Remove cleaned request metadata from payload

---

lib/notification.js
lib/utils.js
test/utils.js

This PR addresses issue #81. It modifies the `filterObject` method to make a copy of the objects it filters and send those to Bugsnag, rather than operating on the data directly, which can potentially break the calling code that is being monitored by Bugsnag.

Clone Objects Before Filtering and Sending to Bugsnag

---

lib/error.js

Simplest way to create a custom Error class in Javascript is to modify the name property of the error instance. With the previous implementation the bugsnag error code would prefer the constructor's name (which is always "Error") over the custom error name which is the desired one.
This change just switches them around so the error.name is considered first and should be the source of truth, and only if it's not defined should fallback to constructor.name.
The previous way made it difficult to work with error libraries like: https://github.com/jshttp/http-errors
Also worth mentioning: the bugsnag notify does allow you to specify a custom errorClass in the function call but it can't be used with, for example, the express errorHandler as it captures the errors automatically.

Prefer error.name over error.constructor.name

---

lib/bugsnag.js
lib/notification.js

This PR ensures that the `callback` argument on the `notify` function is invoked with an error as the first argument when the event is prevented from being sent to Bugsnag.
The situations & their messages are;
- When an API key is not supplied.  
> Error: Bugsnag has not been configured with an api key!
- If the release stage is not included in the `notifyReleaseStages` array.  
> Error: Current release stage not permitted to send events to Bugsnag.
- If a `beforeNotify` callback prevents the event from being sent.  
> Error: At least one beforeNotify callback prevented the event from being sent to Bugsnag.
Fixes #74

Invoke notify callback with errors

---

lib/bugsnag.js

Added support to `createErrorHandler` and `createRequestHandler`.  Both methods have the same signature as `bugsnag.register` (apiKey, options).
Should I add tests cases to these new methods? I am not seeing test-cases for other methods in the `lib/bugsnag` file.
It is ok to call `bugsnag.register` multiple times? Should we verify if it was already called and just configure once?
Where the docs are updated?
Just let me know what do you think of this
Thanks

Create express middlewares factories.

---

lib/bugsnag.js
lib/notification.js
test/notification.js

Sometimes additional context available on the error instance is needed when creating error reports, which can then be used to attach metadata or decide to cancel the report. This change adds the original error which generated the report as a parameter to `beforeNotifyCallbacks`.
Here's an example of attaching custom error properties (from #101) which is then easily fixable:
```js
// Given a custom error type with additional properties
function SpecialError(message) {
this.name = "SpecialError";
this.message = message;
this.customInfo = {times: "three"};
this.otherInfo = {bananas: 4};
}
SpecialError.prototype = Object.create(Error.prototype);
// Additional fields can then be attached to the metadata of a report
Bugsnag.onBeforeNotify(function (notification, error) {
var customInfo = {}; …
```

Pass original error to pre-send callbacks

---

lib/utils.js
test/utils.js

This commit addresses performance issues in Utils.filterObject. When
filtering objects of moderate size the old logic would hang the program
for multiple seconds. Also adds support for filtering objects in arrays
and handling more complex references.

Utils: Improve and correct filter/clone

---

package.json

stack-trace was recently updated https://github.com/felixge/node-stack-trace/releases/tag/v0.0.10

allow newer versions of stack-trace

---

lib/notification.js
package.json
test/notification.js

Added a few tests for avoiding circular references when serializing a `Notification` to JSON. It revealed some false positives around sibling objects, and generally poor performance overall since a reference to every object encountered is kept until the process is complete. 
The existing serialization and cycle detection logic was replaced with [`json-stringify-safe`](https://github.com/isaacs/json-stringify-safe), which handles the test cases correctly.
Fixes #96

Add tests for serializing a payload, improve performance

---

lib/bugsnag.js
lib/utils.js
test/notification.js
test/utils.js

`notify(err…)` now catches and reports the case where `err=null|undefined|0|true|false`.
An error-level log is printed and Error is constructed and sent to Bugsnag with the offending parameter. All of the arguments are captured and sent in the report's metadata too, to help provide context for when this happens.

Handle and report invalid notify(err) argument. Fixes #110.

---

lib/bugsnag.js
lib/configuration.js
test/lib/process-uncaught-exception.js
test/lib/process-unhandled-rejection.js
test/notification.js

Unhandled Promise rejections are now dealt with in the same way as uncaught exceptions:
- error is sent to Bugsnag
- error is logged
- process is shut down with a non-zero exit code (1)
Although this is a _"good"_ change, this can be definitely be considered a breaking change. Recovering from unhandled promise rejections is, as with uncaught exceptions, a terrible idea but if people are relying their processes to continue after such conditions, this change will break that behaviour.
So even though this is a very minor feature addition, this should be a semver major release in my opinion.

Auto unhandled rejection

---

lib/bugsnag.d.ts

Looks like the TypeScript definitions haven't caught up to the work that was done in #103 yet. This PR just updates the definition for `onBeforeNotify` so that it can optionally accept the original error as the second parameter.

add error param to types for onBeforeNotify callback

---

lib/notification.js

Support older versions of Bugsnag on-premise that expect the error report contain the `apiKey` parameter in the body.

Ensure apiKey is sent in request body

---

lib/notification.js
test/notification.js

This PR ensures the values in `Configuration.filters` get applied to all places where sensitive issues could exist.
Fixes #127.

Apply metaData filters to request, app, user, device and breadcrumbs

---

lib/request_info.js

This PR ensures `req.connection.address()` is not called if `req.connection.address`  is `undefined`.
Fixes #129.

Don't call req.connection.address() if address is undefined

---

lib/utils.js
package.json
test/utils.js

When `Utils.cloneObject()` was called on an instance of a class, such as the mongo driver's `ObjectId` instance, the copy would bring across its enumerable private properties, but none of its methods, resulting in a bad serialization like so:
"id": {
"id": {
"0": 88,
"1": 129,
"2": 222,
"3": 117,
"4": 187,
"5": 221,
"6": 189,
"7": 57,
"8": 86,
"9": 86,
"10": 65,
"11": 202
},
"bsontype": "ObjectID"
}
Now just before cloning, objects are checked for a toJSON() method. If they have one, the result of that is used for the clone resulting in better serialization, such as:
{ "oid": "5a9045f5be123c8c5d811d35" }

Better preparation for cloned object serialization

---

lib/bugsnag.js
lib/configuration.js

```
Bugsnag:  Error: flop
at Object.<anonymous> (/Users/bengourley/Development/bugsnag-node/scratch/sig.js:3:7)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)
at Function.Module.runMain (module.js:609:10)
at startup (bootstrap_node.js:158:16)
at bootstrap_node.js:578:3
```
```
Bugsnag:  Encountered an uncaught error, terminating…
Error: flop
at Object.<anonymous> (/Users/bengourley/Development/bugsnag-node/scratch/sig.js:7:7)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)
at …
```

Improve logging clarity for unhandled exceptions

---

lib/configuration.js
lib/notification.js
test/notification.js

The error reporting payload supports app.type but this notifier didn't provide a way to set it. This change allows the app type setting to be set with the config option "appType".
Fixes #126.

feat(config): Support configuration of appType

---

lib/bugsnag.d.ts

With 2.4.0 the way in which URLs are configured has been changed. It looks like these types have not been updated in a while so I went through the documentation and updated them. I've added more detailed types to some of the properties that were `any` types. Lastly I've organized them alphabetically.
- `appType`
- `autoCaptureSessions`
- `autoNotifyUnhandledRejection`
- `endpoints`
- `sessionEndpoint`
- `logger`
I changed this locally in my codebase and the types were recognized. That being said, I'm not using most of the options here, just 1 or two.
I could contribute this to DefinitelyTyped instead
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:

Fix types for the configuration object

---

lib/bugsnag.d.ts

In PR #144, the types for the TypeScript `Logger` interface were added, however the logger methods are missing return types.  This means TypeScript treats the return as implicit `any`, and for projects configured to not allow implicit `any`, that breaks the build.  The errors look like:
```
node_modules/bugsnag/lib/bugsnag.d.ts(54,9): error TS7010: 'info', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/bugsnag/lib/bugsnag.d.ts(55,9): error TS7010: 'warn', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/bugsnag/lib/bugsnag.d.ts(56,9): error TS7010: 'error', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/bugsnag/lib/bugsnag.d.ts(57,9): error TS7010: 'debug', which lacks …
```

Fix TypeScript types: add a return type to logger methods
